// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8CLIX7A7m1DBJnFJ3PSfr9HeIMyrpx8I',
    appId: '1:118334184799:web:be97e73928e9dc4ce62aea',
    messagingSenderId: '118334184799',
    projectId: 'spiderman-57200',
    authDomain: 'spiderman-57200.firebaseapp.com',
    storageBucket: 'spiderman-57200.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3yFyE0rTrP9v1xsgl9FXwluyPkhrBqhE',
    appId: '1:118334184799:android:228dc4ba3a269c8fe62aea',
    messagingSenderId: '118334184799',
    projectId: 'spiderman-57200',
    storageBucket: 'spiderman-57200.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfbrB7DN-VGZZ5tywgEhoc3x8ArnWukIU',
    appId: '1:118334184799:ios:94b3d1ed3dbd9e38e62aea',
    messagingSenderId: '118334184799',
    projectId: 'spiderman-57200',
    storageBucket: 'spiderman-57200.firebasestorage.app',
    iosBundleId: 'com.example.spiderman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfbrB7DN-VGZZ5tywgEhoc3x8ArnWukIU',
    appId: '1:118334184799:ios:94b3d1ed3dbd9e38e62aea',
    messagingSenderId: '118334184799',
    projectId: 'spiderman-57200',
    storageBucket: 'spiderman-57200.firebasestorage.app',
    iosBundleId: 'com.example.spiderman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8CLIX7A7m1DBJnFJ3PSfr9HeIMyrpx8I',
    appId: '1:118334184799:web:08b23733b43d22d3e62aea',
    messagingSenderId: '118334184799',
    projectId: 'spiderman-57200',
    authDomain: 'spiderman-57200.firebaseapp.com',
    storageBucket: 'spiderman-57200.firebasestorage.app',
  );
}
